### ISSUE TITLE
Units unclear

### ISSUE THREAD

**Issue by juhaszp95** [quartiq/stabilizer-stream#13]
Hi There,

I've been playing around with the crate, and I have a question regarding units, specifically the 'integrated RMS'.

I haven't been able to figure out what this is - this seems simply like an integral of the power density spectrum, but it doesn't say what the units are, and it always seems to be positive (even if the power density spectrum (in dB) is negative).

For example, I've put in a 10 kHz sine wave with 5 V peak-to-peak amplitude (i.e. 2.5 V amplitude), and the integrator itegrates up to ca. 3.55. I have no idea how this number is obtained. I wonder if you could enlighten what this integrated RMS is?

**Comment by jordens** [comment]
The integral of a power spectral density is power. "Integrated RMS" is the square root of the integrated power spectral density, i.e. the root mean square fluctuations of the underlying quantity over some band. Only positive quantities (e.g. a spectral power) can be shown on a log scale. The mean/sum/integral of a positive quantity is positive (their integral is also monotonically increasing). The square root of a positive quantity is positive (and monotonically increasing). Normalization is such that for a PSD of `p` flat over a bandwidth `b` the integrated RMS is `sqrt(p*b)`, e.g. for `0dB/Hz` white noise in a `1 Hz` band, the RMS fluctuation is `1`. For a unit amplitude sine the power is `1/2` (peak and integrated) and the RMS is `1/sqrt(2)`.

If you are certain about the physical amplitude in your case, maybe the stream serialization/deserialization has a factor of two wrong for `dual-iir` data: we use this tool primarily for other applications and haven't tested it much for `dual-iir`.

**Comment by juhaszp95** [comment]
Ah, so essentially this is RMS power in watts assuming a 1 ohm load (and then displayed as a frequency component up to which you integrate)? (Which could be a negative number, if it was in dB, but it isn't then.)

**Comment by jordens** [comment]
The units are those of the base quantity. Volt in the case of dual-iir stream.

**Comment by juhaszp95** [comment]
I see.
However, I think your terminology is rather confusing: it's not an integrated RMS power that you're plotting, but an integrated RMS amplitude -- power is usually taken to be proportional to the square of the amplitude. Furthermore, it's quite confusing that the PSD is in dB/Hz, but the integrated RMS is being shown in native units, not dB.

My understanding of what's happening now is this: you calculate the FFT of the signal (squared?), and then integrate that FFT up to a given frequency, and show the RMS amplitude of that signal as a function of the frequency you integrate up to. Importantly, it seems to me that this is not a power. Take a signal $V(t)=\sin(2\pi t/T)$, the power associated with this is  $P(t)=V^2(t)=\sin^2(2\pi t/T)$. The average power is $1/2$. The root-mean-square voltage is $1/\sqrt{2}$. So, when you put in a 1 V amplitude, 1 kHz signal, this gets RMS'ed into $1/\sqrt{2}\approx 0.7\text{ V}$, which is what is reported in the GUI as you integrate up to high frequencies. (If this was the power corresponding to the integrated RMS voltage, it would report $1/2$.)

Therefore:
- Could you confirm that my understanding is correct, and give some mathematical formulas as to how you calculate the PSD (is that also an amplitude or an amplitude-squared FFT)?
- Perhaps you would want to display the integrated RMS in dB, not in native units, to make it consistent with the PSD (or at least draw attention to the discrepancy).
- Clarify that it's an integrated RMS of the amplitude, not the power.

**Comment by jordens** [comment]
It doesn't claim "integrated RMS power" anywhere. That's your invention.
I'm really confused by your repetition of what I said above. What are you trying to achieve and what's the problem?
Regarding your request (and even command!): I fear your understanding of basic signal processing concepts is not complete and/or incorrect. The formulas are in the code and above. If you need further help with signal processing basics, I'd recommend books or courses.
dB for an integrated RMS plot would be plain wrong. There is no need (and no way) to plot it in the same units as PSD. The intent is precisely in the different units.
I'll just ignore you ordering me to do things.
