### ISSUE TITLE
Update backend to utilize Websockets

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/stabilizer-stream#5]
Currently, the backend server serializes data and serves it via REST. This can cause significant delays due to serialization of large data arrays, which results ultimately in dropping of inbound stream frames. Utilizing [tide-websockets](https://crates.io/crates/tide-websockets) will allow us to avoid serialization of this data (since we can use a [`TypedArray`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) around the binary data in Javascript.

**Comment by jordens** [comment]
Closing as not pertinent to the current state of the code.
The current code is a single monolithic userspace application.
