### ISSUE TITLE
Captures won't display with long capture periods

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/stabilizer-stream#6]
For capture periods longer than ~150ms, the capture doesn't appear at all. Investigation of the console log indicates that Javascript hits a memory exception and drops the serialized data.

This should be resolved either by limiting the size of the data sent to the front end (limiting number of points) or by drawing the display in chunks of a specific size.

**Comment by jordens** [comment]
Closing as not pertinent to the current state of the code.
No time domain display/analysis is currently present.
