### ISSUE TITLE
Capture window may not be respected

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/stabilizer-stream#7]
When requesting a capture for 10ms of data, the server will provide 10ms worth of _samples_. If samples are dropped in the middle, this means that there may be data spanning an undefined amount of time.

This is undesired because it means that we cannot consistently display the data with a fixed time window, as the maximum timestamp changes based on whether or not data was dropped.

**Comment by jordens** [comment]
Closing as not pertinent to the current state of the code.
Triggering has been removed.
