### ISSUE TITLE
Add edge trigger support

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/stabilizer-stream#8]
Add support for triggering captures based on a single edge trigger mechanism.

The edge trigger should allow the following:
* Edge trigger time support (e.g. set the edge to 0-100% of the capture window)
* Support rising/falling triggers on a specific trace label
* Utilize the standard 30%/50%/70% edge trigger mechanism, where the waveform must rise from below 30% max, cross 50%, and then exceed 70% to define a valid "edge". The trigger time is defined as the point that crosses 50%.

**Comment by jordens** [comment]
Closing as not pertinent to the current state of the code.
Time domain analysis/display has been removed.
