### ISSUE TITLE
Add configurable decimation support

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/stabilizer-stream#9]
Add support for decimating the data server-side. This will allow us to immediately decimate in-bound data.

Decimation may either be done automatically, or via input provided from the UI.

This may help resolve https://github.com/quartiq/stabilizer-streaming/issues/6 by limiting the number of samples sent to the frontend.

**Comment by jordens** [comment]
Closing as not pertinent to the current state of the code.
There is infinitly deep staged decimation implemented and available.
